# Generated by Django 2.1 on 2019-09-24 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(max_length=200, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 24, 12, 44, 27, 12872), verbose_name='date published'),
        ),
    ]
