# Generated by Django 2.1 on 2019-09-30 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190927_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 14, 27, 48, 793315), verbose_name='date published'),
        ),
    ]
