# Generated by Django 2.1 on 2019-09-30 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190930_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 15, 6, 50, 85127), verbose_name='date published'),
        ),
    ]
