# Generated by Django 2.1 on 2019-10-02 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190930_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 13, 57, 50, 97201), verbose_name='date published'),
        ),
    ]
