# Generated by Django 2.1 on 2019-10-02 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191002_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 15, 5, 8, 432757), verbose_name='date published'),
        ),
    ]
