# Generated by Django 2.1 on 2019-10-03 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191002_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 18, 24, 5, 61516), verbose_name='date published'),
        ),
    ]
