# Generated by Django 2.1 on 2019-10-28 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191003_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 20, 39, 52, 1965), verbose_name='date published'),
        ),
    ]
